/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra11curpgrafico;

import java.util.Random;

/**
 *
 * @author sarah
 */
public class Grafico extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */
    public Grafico() {
        initComponents();
    }
    private String nombre;
    private String paterno;
    private String materno;
    private String genero;
    private String dia;
    private String mes;
    private String año;
    private String estado;
    private String estados;
    private String resultado;
    private int folio;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAño = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTPaterno = new javax.swing.JTextField();
        jTMaterno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBoxDia = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jTResultado = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLabelFolio = new javax.swing.JLabel();
        jLabelEntidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("Nombre");

        jLabel3.setText("Primer apellido");

        jLabel4.setText("Segundo apellido");

        jLabel5.setText("Día de nacimiento");

        jLabel6.setText("Mes de nacimiento");

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel7.setText("Año de nacimiento");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mujer", "Hombre" }));

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aguascalientes", "Baja California", "Baja California del sur ", "Campeche", "Coahuila", "Colima", "Chiapas", "Chihuahua", "Ciudad de México", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "México", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas", "Nacio en el extranjero", " " }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo");

        jLabel9.setText("Estado");

        jTMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMaternoActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTMaterno))
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTPaterno))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 630));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 20));
        jPanel2.add(jTResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, 20));
        jPanel2.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 80, 20));
        jPanel2.add(jLabelFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 70, 10));

        jLabelEntidad.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel2.add(jLabelEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra11curpgrafico/curp1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 560, 640));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 520, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMaternoActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nombre = jTNombre.getText();
        nombre=nombre.toUpperCase();
        String l1 = String.valueOf(nombre.charAt(0));
        l1 = l1.toUpperCase();
        String n = String.valueOf(nombre.charAt(2));
        n = n.toUpperCase();
        paterno = jTPaterno.getText();
        paterno=paterno.toUpperCase();
        String p1 = String.valueOf(paterno.charAt(0));
        p1 = p1.toUpperCase();
        String p = String.valueOf(paterno.charAt(2));
        p = p.toUpperCase();
        String p2 = String.valueOf(paterno.charAt(1));
        p2 = p2.toUpperCase();
        materno = jTMaterno.getText();
        materno=materno.toUpperCase();
        String l3 = String.valueOf(materno.charAt(0));
        l3 = l3.toUpperCase();
        String m = String.valueOf(materno.charAt(2));
        m = m.toUpperCase();
        genero = String.valueOf(jComboBoxSexo.getSelectedItem());
        String ge = String.valueOf(genero.charAt(0));
        ge = ge.toUpperCase();

        dia = String.valueOf(jComboBoxDia.getSelectedItem());

        String dia1 = String.valueOf(dia.charAt(0));
        String dia2 = String.valueOf(dia.charAt(1));

        mes = String.valueOf(jComboBoxMes.getSelectedItem());

        String m1 = String.valueOf(mes.charAt(0));
        String m2 = String.valueOf(mes.charAt(1));

        año = jTextFieldAño.getText();
        String anio = (año.substring(2));
        estados=String.valueOf(jComboBoxEstado.getSelectedItem());
        estados=estados.toUpperCase();
       estado=estados;

        //estado
        if (estados.endsWith("Aguascalientes")) {
            estado = "AS";
        } else if (estados.endsWith("Baja California")) {
            estado = "BC";
        } else if (estados.endsWith("BajaCalifornia Sur")) {
            estado = "BS";
        } else if (estados.endsWith("Campeche")) {
            estado = "CC";
        } else if (estados.endsWith("Coahuila")) {
            estado = "CL";
        } else if (estados.endsWith("Colima")) {
            estado = "CM";
        } else if (estados.endsWith("Chiapas")) {
            estado = "CS";
        } else if (estados.endsWith("Chihuahua")) {
            estado = "CH";
        } else if (estados.endsWith("Ciudad de México")) {
            estado = "DF";
        } else if (estados.endsWith("Durango")) {
            estado = "DG";
        } else if (estados.endsWith("Guanajuato")) {
            estado = "GT";
        } else if (estados.endsWith("Guerrero")) {
            estado = "GR";
        } else if (estados.endsWith("Hidalgo")) {
            estado = "HG";
        } else if (estados.endsWith("Jalisco")) {
            estado = "JC";
        } else if (estados.endsWith("México")) {
            estado = "MC";
        } else if (estados.endsWith("Michoacán")) {
            estado = "MN";
        } else if (estados.endsWith("Morelos")) {
            estado = "MS";
        } else if (estados.endsWith("Nayarit")) {
            estado = "NT";
        } else if (estados.endsWith("Nuevo León")) {
            estado = "NL";
        } else if (estados.endsWith("Oaxaca")) {
            estado = "OC";
        } else if (estados.endsWith("Puebla")) {
            estado = "PL";
        } else if (estados.endsWith("Queretaro")) {
            estado = "QT";
        } else if (estados.endsWith("QuintanaRoo")) {
            estado = "QR";
        } else if (estados.endsWith("San Luis Potosí")) {
            estado = "SP";
        } else if (estados.endsWith("Sinaloa")) {
            estado = "SL";
        } else if (estados.endsWith("Sonora")) {
            estado = "SR";
        } else if (estados.endsWith("Tabasco")) {
            estado = "TC";
        } else if (estados.endsWith("Tamaulipas")) {
            estado = "TS";
        } else if (estados.endsWith("Tlaxcala")) {
            estado = "TL";
        } else if (estados.endsWith("Veracruz")) {
            estado = "VZ";
        } else if (estados.endsWith("Yucatán")) {
            estado = "YN";
        } else if (estados.endsWith("Zacatecas")) {
            estado = "ZS";
        } else if (estados.endsWith("Nacido en el Extranjero")) {
            estado = "NE";
        } else {
            estado = "NE";
        }

        resultado = p1 + p2 + l3 + l1 + anio + m1 + m2 + dia1 + dia2 + ge + estado + p + m + n;
   
        jTResultado.setText(resultado);
        jLNombre.setText(nombre+" "+paterno+" "+materno);
        jLFecha.setText(dia+"/"+mes+"/"+año);
        jLabelEntidad.setText(estados);
       folio=2345678;
        jLabelFolio.setText("3456789");
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxDia;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEntidad;
    private javax.swing.JLabel jLabelFolio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTMaterno;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPaterno;
    private javax.swing.JLabel jTResultado;
    private javax.swing.JTextField jTextFieldAño;
    // End of variables declaration//GEN-END:variables
}
